### PR TITLE
Cf hosted argo flow

### PR DESCRIPTION
**Pull request by NimRegev**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/cf-hosted-argo-flow/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/cf-hosted-argo-flow/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/cf-hosted-argo-flow/docs/

**Comment by cf-ci-bot-v2** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/cf-hosted-argo-flow/docs/

**Comment by cf-ci-bot-v2** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/cf-hosted-argo-flow/docs/

**Pull request merged**
