### PR TITLE
Nima capdocs

### PR DESCRIPTION
**Pull request by NimRegev**
Recommitting to make sure changes are in

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/nima-capdocs/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/nima-capdocs/docs/

**Comment by NimRegev** [comment]
Resolved conflicts

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/nima-capdocs/docs/

**Pull request merged**
