### PR TITLE
Update add-users.md

### PR DESCRIPTION
**Pull request by NimRegev**
Rewrote topic

### CODE REVIEW

**Comment by itai-codefresh** [comment]
hey

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/nima-capdocs/docs/

**Comment by itai-codefresh** [comment]
you have many placesholders and all sorts of unfinished work seems like, are you sure this is ready to push?

**Comment by NimRegev** [comment]
> 

No way is it ready for push. do i set a meeting with you/Kostis to get answers? Or can you add feedback on the page itself?

**Comment by NimRegev** [comment]
Oops that was a mistake

**Comment by NimRegev** [comment]
Rewrote add users topic

**Pull request merged**
