### PR TITLE
main concepts

### PR DESCRIPTION
**Pull request by itai-codefresh**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-8014-main-concepts/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-8014-main-concepts/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://cap-staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-8014-main-concepts/docs/

**Comment by NimRegev** [comment]
Edited initial version

**Pull request merged**
